spring:
 mvc:
  pathmatch:
    matching-strategy: ant_path_matcher
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
##          jwk-set-uri: http://localhost:8080/oauth2/jwks
#          issuer-uri: http://localhost:8080